{% set name = "timezonefinder" %}
{% set version = "6.1.1" %}
{% set sha256 = "406bea77a7baec5e2b1c2b4793ff8f40c174b6d8e894631e60864d956139afef" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv
#  noarch: python

requirements:
  build:
    - poetry
    - cffi
    - setuptools
    - {{ compiler('c') }}
  host:
    - pip
    - python 3
    - poetry
  run:
    - python 3
    - numpy
    - h3-py
    - numba
    - cffi

test:
  imports:
    - timezonefinder
    - timezonefinder.timezonefinder

about:
  home: https://timezonefinder.michelfe.it/gui
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: fast python package for finding the timezone of any point on earth (coordinates) offline
  description: |
    This is a fast and lightweight python package for looking up the corresponding timezone for given 
    corresponding timezone for a given lat/lng on earth entirely offline.

  dev_url: https://github.com/jannikmi/timezonefinder

extra:
  recipe-maintainers:
    - snowman2
    - jannikmi
