{% set name = "timezonefinder" %}
{% set version = "6.1.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/timezonefinder-{{ version }}.tar.gz
  sha256: 8d0b5839250669f2546c4785a35b85bd93b964152176bdbcf137c12c3e1e4246

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - poetry-core >=1.0.0
    - cffi
    - setuptools
    - pip
  run:
    - python
    - numpy >=1.18,<2
    - h3-py >=3.7.6,<4
    - cffi >=1.15.1,<2
    - setuptools >=65.5
  run_constrained:
    - numba >=0.56,<1

test:
  imports:
    - timezonefinder
    - timezonefinder.timezonefinder
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://timezonefinder.michelfe.it/gui
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: fast python package for finding the timezone of any point on earth (coordinates) offline
  description: |
    This is a fast and lightweight python package for looking up the corresponding timezone for given 
    corresponding timezone for a given lat/lng on earth entirely offline.

  dev_url: https://github.com/jannikmi/timezonefinder

extra:
  recipe-maintainers:
    - xylar
    - snowman2
    - jannikmi
