{% set name = "timezonefinder" %}
{% set version = "3.1.0" %}
{% set sha256 = "ffcddd733871907a7a8c138fa8ccc42c44cbf16bf591f367531a0a049ad46a4a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - numpy
    - numba
    - six

test:
  imports:
    - timezonefinder
    - timezonefinder.timezonefinder
    - timezonefinder.helpers
    - timezonefinder.functional

about:
  home: https://github.com/MrMinimal64/timezonefinder
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A lightweight python library for finding the timezone of any point on earth (coordinates), but fast! '
  description: |
    This is a fast and lightweight python project for looking up the
    corresponding timezone for a given lat/lng on earth entirely offline.

    This project is derived from and has been successfully tested against
    pytzwhere (github), but aims at providing improved performance and usability.
  dev_url: https://github.com/MrMinimal64/timezonefinder

extra:
  recipe-maintainers:
    - snowman2
