{% set name = "timezonefinder" %}
{% set version = "6.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/timezonefinder-{{ version }}.tar.gz
  sha256: 3027ee5516c4c24cd332393dee9a2195bc4ffd2ff090e2c01a966fe64c18b6a6

build:
  script: {{ PYTHON }} -m pip install . -vv --no-dev --no-build-isolation
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cffi                                   # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - poetry-core >=1.0.0
    - cffi
    - setuptools
    - pip
  run:
    - python
    - numpy >=1.21,<3  # [py<39]
    - numpy >=1.23,<3  # [py>=39]
    - h3-py >=3.7.6,<4
    - cffi >=1.15.1,<2
    - setuptools >=65.5
  run_constrained:
    - numba >=0.56,<1  # [py<312]
    - numba >=0.59,<1  # [py>=312]
    - pytz >=2022.7.1

test:
  imports:
    - timezonefinder
    - timezonefinder.timezonefinder
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://timezonefinder.michelfe.it/gui
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: python package for finding the timezone of any point on earth (coordinates) offline
  description: |
    This is a fast and lightweight python package for looking up the corresponding timezone for given 
    corresponding timezone for a given lat/lng on earth entirely offline.

  dev_url: https://github.com/jannikmi/timezonefinder

extra:
  recipe-maintainers:
    - xylar
    - snowman2
    - jannikmi
