{% set name = "timezonefinder" %}
{% set version = "8.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/timezonefinder-{{ version }}.tar.gz
  sha256: a88beb09a8e24d32b522c9e70c37d633697477e7c436dfaebe24d8e155c81bbb

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cffi                                   # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - cffi
    - setuptools >=61
    - pip
  run:
    - python
    - numpy >=1.23,<3
    - h3-py >4
    - cffi >=1.15.1,<2
    - python-flatbuffers >=25.2.10
  run_constrained:
    # numba extra
    - numba >=0.56,<1  # [py<312]
    - numba >=0.59,<1  # [py>=312]
    # pytz extra
    - pytz >=2022.7.1

test:
  imports:
    - timezonefinder
    - timezonefinder.timezonefinder
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://timezonefinder.michelfe.it/gui
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: python package for finding the timezone of any point on earth (coordinates) offline
  description: |
    This is a fast and lightweight python package for looking up the corresponding timezone for given 
    corresponding timezone for a given lat/lng on earth entirely offline.

  dev_url: https://github.com/jannikmi/timezonefinder

extra:
  recipe-maintainers:
    - xylar
    - snowman2
    - jannikmi
