schema_version: 1

context:
  name: timezonefinder
  version: "9.0.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/timezonefinder-${{ version }}.tar.gz
  sha256: c21c47f1463320eda57c4cbb5b80e875b80e64d6b78e73477e0f8bdc1a112c04

build:
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  skip:
    - match(python, '<3.11')

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - cffi
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
  host:
    - python
    - pip
    - setuptools >=62.3
    - cffi
  run:
    - python
    - numpy >=2
    - h3-py >=4
    - cffi >=1.15.1,<3
    - python-flatbuffers >=25.2.10
    - timezonefinder-data >=3.2026.3.post1,<4

tests:
  - python:
      imports:
        - timezonefinder
        - timezonefinder.timezonefinder
      pip_check: true

about:
  homepage: https://timezonefinder.michelfe.it/gui
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: python package for finding the timezone of any point on earth (coordinates) offline
  description: |
    This is a fast and lightweight python package for looking up the corresponding timezone for given
    corresponding timezone for a given lat/lng on earth entirely offline.

  repository: https://github.com/jannikmi/timezonefinder

extra:
  recipe-maintainers:
    - xylar
    - snowman2
    - jannikmi
